--Week10 Lecture
--DDL - Data Definition Language
--DML- Data Manipulation Language

--Creation Scripts

--Create Tables first with no foreign key relationship

--ROLES
--DDL
CREATE TABLE zzlstRoles(
    rolename VARCHAR(25) Primary Key);
    
--DML
INSERT INTO zzlstRoles (rolename) VALUES ('Actor'); 
INSERT INTO zzlstRoles (rolename) VALUES ('Actress');
INSERT INTO zzlstRoles (rolename) VALUES ('Director');
INSERT INTO zzlstRoles (rolename) VALUES ('Executive Director');

--PEOPLE

CREATE TABLE zzDatPeople (
    personID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    first_name varchar(20) NOT NULL, 
    last_name varchar(30) NOT NULL, 
    DateOfBirth date, 
    City varchar(25) DEFAULT('Los Angeles'));
    
INSERT INTO zzDatPeople (first_name, last_name, DateOfBirth, City)
    VALUES ('Rohil', 'Khakhar', to_date('19980516', 'yyyymmdd'), '');
    
INSERT INTO zzDatPeople (first_name, last_name, DateOfBirth, City)
    VALUES ('Dmitri', 'Zenit', to_date('19970512', 'yyyymmdd'), 'Great White North');

INSERT INTO zzDatPeople (first_name, last_name, DateOfBirth, City)
    VALUES ('Awesome', 'Manchester', to_date('19990512', 'yyyymmdd'), ' ');
    
--DDL for MOVIES

CREATE TABLE zzDatMovies (
    movieID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title varchar(75) NOT NULL, 
    production_year int CHECK (production_year BETWEEN 1900 AND 2050), 
    budget decimal (15, 2) DEFAULT(0.00), 
    "length" int);
    
CREATE TABLE zzmovieroles (
    roleID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    movieID int, 
    personID int, 
    rolename varchar(25));
    
INSERT INTO zzdatmovies (title, production_year, budget, "length")
    VALUES('Great White North', 1985, 10000, 85);
    
ALTER TABLE zzmovieroles ADD CONSTRAINT fk_roles_movies FOREIGN KEY (movieID) REFERENCES zzdatmovies(movieID);
ALTER TABLE zzmovieroles ADD CONSTRAINT fk_roles_people FOREIGN KEY (personID) REFERENCES zzDatPeople(personID);
ALTER TABLE zzmovieroles ADD CONSTRAINT fk_roles_rolenames FOREIGN KEY (rolename) REFERENCES zzlstRoles(rolename);

--Now, DML

INSERT INTO zzmovieroles (movieID, personID, rolename)
    VALUES (1, 2, 'Actor');
    